name: Go Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets: inherit

  test:
    needs: terraform
    uses: ./.github/workflows/go_test.yml
    with:
      app-ip: ${{ needs.terraform.outputs.app_ip }}
      db-endpoint: ${{ needs.terraform.outputs.db_endpoint }}
      db-port: ${{ needs.terraform.outputs.db_port }}
      sg-ssh-id: ${{ needs.terraform.outputs.sg_ssh_id }}
    secrets: inherit

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.22']
    steps:
    - uses: actions/checkout@v4 # Atualizado para v4

    - name: Build
      run: go build -v main.go

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-app
        path: |
          main
          templates/
  
  deploy_ec2:
    needs: [terraform, build]
    uses: ./.github/workflows/ec2.yml
    with:
      app-ip: ${{ needs.terraform.outputs.app_ip }}
      db-endpoint: ${{ needs.terraform.outputs.db_endpoint }}
      sg-ssh-id: ${{ needs.terraform.outputs.sg_ssh_id }}
    secrets: inherit