name: Go Test Pipeline

on:
  workflow_call:
    inputs:
      app-ip:
        description: "IP público da instância onde a API será implantada"
        required: true
        type: string
      db-endpoint:
        description: "Endpoint do RDS"
        required: true
        type: string
      db-port:
        description: "Porta do banco de dados"
        required: true
        type: string
      sg-ssh-id:
        description: "ID do Security Group de acesso SSH"
        required: true
        type: string


permissions:
  id-token: write 
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.22']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    
    - name: Get GitHub Runner IP
      id: ip
      run: echo "ipv4=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT
    
    # Substituído por inputs.sg-ssh-id
    - name: Whitelist Runner IP
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ inputs.sg-ssh-id }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32  

    # Substituído por inputs.app-ip
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ inputs.app-ip }}" >> ~/.ssh/known_hosts

    # Substituído por inputs.db-endpoint, inputs.db-port e inputs.app-ip
    - name: Create SSH Tunnel
      run: |
        ssh -N -L 5432:${{ inputs.db-endpoint }}:${{ inputs.db-port }} ubuntu@${{ inputs.app-ip }} &

    - name: Test
      env:
        DB_HOST: "127.0.0.1"
        DB_PORT: "5432"
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        sleep 5 
        go test -v ./...
    
    # Substituído por inputs.sg-ssh-id
    - name: Revoke Runner IP
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ inputs.sg-ssh-id }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32